trigger: none

pool: cicdpool

jobs:
- job: ci

  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        npm install
        npm run build

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: 'react-build'

- job: cd
  dependsOn: ci
  steps:

  # STEP 1 - Download artifact
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'react-build'
      targetPath: '$(Pipeline.Workspace)/react-build'
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'frontend-sc-ssh'
      sourceFolder: '$(Pipeline.Workspace)/react-build'
      contents: '*.zip'
      targetFolder: '/home/azureuser/deploy'
      readyTimeout: '20000'

  - task: SSH@0
    inputs:
      sshEndpoint: 'frontend-sc-ssh'
      runOptions: 'inline'
      inline: |
        sudo apt update
        sudo apt install nginx unzip -y
        
        sudo rm -rf /var/www/html/*
        
        sudo unzip -o /home/azureuser/deploy/*.zip -d /var/www/html/
        
        sudo systemctl restart nginx
        sudo systemctl enable nginx
      readyTimeout: '20000'
      
