trigger: none

pool:
  name: cicdpool

stages:
- stage: CD
  displayName: 'Deploy React Application'

  jobs:
  - job: Deploy
    displayName: 'Deploy to Frontend VM'

    steps:

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Latest CI Artifact'
      inputs:
        buildType: 'specific'
        project: 'cicd-infra'
        definition: '6'
        buildVersionToDownload: 'latest'
        artifactName: 'react-build'
        targetPath: '$(Pipeline.Workspace)/react-build'

    - task: SSH@0
      displayName: 'Create Deploy Folder'
      inputs:
        sshEndpoint: 'frontend-sc-ssh'
        runOptions: 'inline'
        inline: |
          mkdir -p $HOME/deploy
          rm -f $HOME/deploy/*.zip

    - task: CopyFilesOverSSH@0
      displayName: 'Copy Artifact to VM'
      inputs:
        sshEndpoint: 'frontend-sc-ssh'
        sourceFolder: '$(Pipeline.Workspace)/react-build'
        contents: '*.zip'
        targetFolder: 'deploy'
        readyTimeout: '20000'

    - task: SSH@0
      displayName: 'Deploy Application'
      inputs:
        sshEndpoint: 'frontend-sc-ssh'
        runOptions: 'inline'
        inline: |
          sudo rm -rf /var/www/html/*

          sudo unzip -o $HOME/deploy/*.zip -d /var/www/html/

          echo "===== Deployed Files ====="
          sudo ls -la /var/www/html

          if [ ! -f /var/www/html/index.html ]; then
              echo "ERROR: index.html not found"
              exit 1
          fi

          sudo systemctl restart nginx